// File generated by FlutterFire CLI / manually configured for:
//   gym-presence-tracker-16edc
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnPr9Tr2bqRvlbcFhD_Eo1DCXF6mnKDt4',
    appId: '1:998204591368:android:ad0fe36ab89f82d146b0bd',
    messagingSenderId: '998204591368',
    projectId: 'gym-presence-tracker-16edc',
    storageBucket: 'gym-presence-tracker-16edc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhBrSHk-qPVppjiE629zp1PMGvVbTanZ4',
    appId: '1:998204591368:ios:3178573b39caf1a246b0bd',
    messagingSenderId: '998204591368',
    projectId: 'gym-presence-tracker-16edc',
    storageBucket: 'gym-presence-tracker-16edc.firebasestorage.app',
    iosBundleId: 'com.covaciu.gymtracker',
  );
}
